[versions]
micronaut = "4.3.10"
micronaut-platform = "4.3.5"
micronaut-docs = "2.0.0"
micronaut-test = "4.0.2"
micronaut-aws = "4.3.0"
micronaut-azure = "5.1.0"
micronaut-gcp = "5.3.0"
micronaut-oracle-cloud = "3.4.0"
micronaut-test-resources = "2.4.0"
micronaut-validation = "4.2.0"
micronaut-logging = "1.2.3"

groovy = '4.0.15'
spock = '2.3-groovy-4.0'
gcp-libraries = '26.34.0'
bytebuddy = '1.14.12'

# Gradle plugins
micronaut-gradle-plugin = "4.3.4"
kotlin-gradle-plugin = "1.9.23"
kotlin-gradle-ksp-plugin = "1.9.23-1.0.19"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-platform = { module = 'io.micronaut.platform:micronaut-platform', version.ref = 'micronaut-platform' }

# AWS
micronaut-aws = { module = 'io.micronaut.aws:micronaut-aws-bom', version.ref = 'micronaut-aws' }
amazon-awssdk-s3 = { module = 'software.amazon.awssdk:s3' }
amazon-awssdk-v1 = { module = 'com.amazonaws:aws-java-sdk-core' }

# Azure
micronaut-azure = { module = 'io.micronaut.azure:micronaut-azure-bom', version.ref = 'micronaut-azure' }
azure-storage-blob = { module = 'com.azure:azure-storage-blob' }

# GCP
micronaut-gcp = { module = 'io.micronaut.gcp:micronaut-gcp-bom', version.ref = 'micronaut-gcp' }
gcp-libraries-bom = { module = 'com.google.cloud:libraries-bom', version.ref = 'gcp-libraries' }
gcp-storage = { module = 'com.google.cloud:google-cloud-storage' }

# Oracle Cloud
micronaut-oracle-cloud = { module = 'io.micronaut.oraclecloud:micronaut-oraclecloud-bom', version.ref = 'micronaut-oracle-cloud' }

# Others
#groovy = { module = 'org.apache.groovy:groovy', version.ref = 'groovy' }
micronaut-test-resources = { module = "io.micronaut.testresources:micronaut-test-resources-bom", version.ref = "micronaut-test-resources" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
micronaut-logging = { module = "io.micronaut.logging:micronaut-logging-bom", version.ref = "micronaut-logging" }

bytebuddy = { module = 'net.bytebuddy:byte-buddy', version.ref = 'bytebuddy' }

# Plugins
gradle-micronaut = { module = 'io.micronaut.gradle:micronaut-gradle-plugin', version.ref = 'micronaut-gradle-plugin' }
gradle-kotlin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin-gradle-plugin' }
gradle-kotlin-ksp = { module = 'com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin', version.ref = 'kotlin-gradle-ksp-plugin' }
