[versions]
micronaut = "4.1.11"
micronaut-platform = "4.1.6"
micronaut-docs = "2.0.0"
micronaut-test = "4.0.2"
micronaut-aws = "4.1.1"
micronaut-azure = "5.0.1"
micronaut-gcp = "5.2.0"
micronaut-oracle-cloud = "3.0.7"
micronaut-validation = "4.1.0"
micronaut-logging = "1.1.2"

groovy = '4.0.15'
spock = '2.3-groovy-4.0'
gcp-libraries = '26.26.0'
testcontainers = '1.19.1'
bytebuddy = '1.14.9'

# Gradle plugins
micronaut-gradle-plugin = "4.1.2"
kotlin-gradle-plugin = "1.9.20"
kotlin-gradle-ksp-plugin = "1.9.20-1.0.14"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-platform = { module = 'io.micronaut.platform:micronaut-platform', version.ref = 'micronaut-platform' }

# AWS
micronaut-aws = { module = 'io.micronaut.aws:micronaut-aws-bom', version.ref = 'micronaut-aws' }
amazon-awssdk-s3 = { module = 'software.amazon.awssdk:s3' }
amazon-awssdk-v1 = { module = 'com.amazonaws:aws-java-sdk-core' }

# Azure
micronaut-azure = { module = 'io.micronaut.azure:micronaut-azure-bom', version.ref = 'micronaut-azure' }
azure-storage-blob = { module = 'com.azure:azure-storage-blob' }

# GCP
micronaut-gcp = { module = 'io.micronaut.gcp:micronaut-gcp-bom', version.ref = 'micronaut-gcp' }
gcp-libraries-bom = { module = 'com.google.cloud:libraries-bom', version.ref = 'gcp-libraries' }
gcp-storage = { module = 'com.google.cloud:google-cloud-storage' }

# Oracle Cloud
micronaut-oracle-cloud = { module = 'io.micronaut.oraclecloud:micronaut-oraclecloud-bom', version.ref = 'micronaut-oracle-cloud' }

# Others
#groovy = { module = 'org.apache.groovy:groovy', version.ref = 'groovy' }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
micronaut-logging = { module = "io.micronaut.logging:micronaut-logging-bom", version.ref = "micronaut-logging" }

testcontainers-bom = { module = 'org.testcontainers:testcontainers-bom', version.ref = 'testcontainers' }

# These 2 need the version.ref, otherwise it fails with :object-storage-aws:test: Could not find org.testcontainers:spock:.
# Which then makes importing the Testcontainers BOM pointless
testcontainers-spock = { module = 'org.testcontainers:spock', version.ref = 'testcontainers' }
testcontainers-localstack = { module = 'org.testcontainers:localstack', version.ref = 'testcontainers' }
bytebuddy = { module = 'net.bytebuddy:byte-buddy', version.ref = 'bytebuddy' }

# Plugins
gradle-micronaut = { module = 'io.micronaut.gradle:micronaut-gradle-plugin', version.ref = 'micronaut-gradle-plugin' }
gradle-kotlin = { module = 'org.jetbrains.kotlin:kotlin-gradle-plugin', version.ref = 'kotlin-gradle-plugin' }
gradle-kotlin-ksp = { module = 'com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin', version.ref = 'kotlin-gradle-ksp-plugin' }
